(function(b){function n(){return function(a){if(a.jquery){var c={};c[0]=jQuery;b.map(a.jquery,function(a){var e=a[0],g=a[1],h=a[2],a=a[3];if(typeof a=="string")a=b.unsafe(a);else for(var k=0;a.length&&k<a.length;k++)a[k]=b.unsafe(a[k]);h=="call"?c[g]=c[e].apply(c[e]._obj,a):h=="attr"?(c[g]=c[e][a],c[g]?c[g]._obj=c[e]:b.debug("unrecognized")):b.debug("unrecognized")})}}}b.log=function(a){window.console?window.console.debug?window.console.debug(a):window.console.log&&window.console.log(a):alert(a)};
b.debug=function(a){if(b.with_default(reddit.debug,!1))return b.log(a)};b.fn.debug=function(){b.debug(b(this));return b(this)};b.redirect=function(a){window.location=a};b.fn.redirect=function(a){b(this).filter("form").find(".status").show().html("redirecting...");if(b(this).attr("target")=="_top"){for(var c=window;c!=c.parent;)c=c.parent;c.location=a}else b.redirect(a);return b(this)};b.refresh=function(){window.location.reload(!0)};b.defined=function(a){return typeof a!="undefined"};b.with_default=
function(a,c){return b.defined(a)?a:c};b.websafe=function(a){typeof a=="string"&&(a=a.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/>/g,"&gt;").replace(/</g,"&lt;"));return a||""};b.unsafe=function(a){typeof a=="string"&&(a=a.replace(/&quot;/g,'"').replace(/&gt;/g,">").replace(/&lt;/g,"<").replace(/&amp;/g,"&"));return a||""};b.uniq=function(a,b){for(var d=[],e={},g=b?b:a.length,h=0;h<a.length&&d.length<g;h++)e[a[h]]||(e[a[h]]=!0,d.push(a[h]));return d};(function(a,c){b.fn.show=function(c,
e){b(this).trigger("onshow");return a.call(this,c,e)};b.fn.hide=function(a,e){b(this).trigger("onhide");return c.call(this,a,e)}})(b.fn.show,b.fn.hide);var m={};b.request=function(a,c,d,e,g,h,k){var i=a,f=d;if(!(rate_limit(a)||window!=window.top&&!reddit.cnameframe&&!reddit.external_frame)){if(!(f=!b.with_default(e,!1)))f=m[i]?!1:m[i]=!0;e=f;c=b.with_default(c,{});d=b.with_default(d,n(i));g=b.with_default(g,"json");typeof d!="function"&&(d=n(i));f=function(a){delete m[i];return d(a)};errorhandler_in=
b.with_default(k,function(){});k=function(a){delete m[i];return errorhandler_in(a)};h=b.with_default(h,!1);if(reddit.post_site)c.r=reddit.post_site;if(reddit.cnameframe)c.cnameframe=1;if(reddit.logged)c.uh=reddit.modhash;c.renderstyle=reddit.renderstyle;e&&b.ajax({type:h?"GET":"POST",url:"/api/"+a,data:c,success:f,error:k,dataType:g})}};rate_limit=function(){var a={vote:333,comment:5E3,ignore:0,ban:0,unban:0,assignad:0},c={},d=b.defined,e=b.with_default,g=Date;return function(b){var k=new g,i=c[b],
f=e(a[b],333);c[b]=k;return d(i)&&k-i<f}}();b.fn.vote=function(a,c,d,e){if(reddit.logged){if(b(this).hasClass("arrow")){var g=b(this).hasClass("up")?1:b(this).hasClass("down")?-1:0,h=b(this).all_things_by_id(),k=h.children().not(".child").find(".arrow"),i=g==1?"up":"upmod";k.filter("."+i).removeClass(i).addClass(g==1?"upmod":"up");i=g==-1?"down":"downmod";k.filter("."+i).removeClass(i).addClass(g==-1?"downmod":"down");reddit.logged&&(h.each(function(){var a=b(this).find(".entry:first, .midcol:first");
g>0?a.addClass("likes").removeClass("dislikes unvoted"):g<0?a.addClass("dislikes").removeClass("likes unvoted"):a.addClass("unvoted").removeClass("likes dislikes")}),b.defined(e)||(e=h.filter(":first").thing_id(),a+=d?"":"-"+e,b.request("vote",{id:e,dir:g,vh:a})));c&&c(h,g)}}else showcover(!0,"vote_"+b(this).thing_id());d&&d.stopPropagation()};b.fn.show_unvotable_message=function(){b(this).thing().find(".entry:first .unvotable-message").css("display","inline-block")};b.fn.thing=function(){return this.parents(".thing:first")};
b.fn.all_things_by_id=function(){return this.thing().add(b.things(this.thing_id()))};b.fn.thing_id=function(a){var a=b.with_default(a,"thing"),c=this.hasClass("thing")?this:this.thing();a!="thing"&&(c=c.find("."+a+":first"));if(c.length)return a=b.grep(c.get(0).className.match(/\S+/g),function(a){return a.match(/^id-/)}),a.length?a[0].slice(3,a[0].length):"";return""};b.things=function(){var a=b.map(arguments,function(a){return".thing.id-"+a}).join(", ");return b(a)};b.fn.same_author=function(){var a=
b(this).thing_id("author"),c=[];b(".author.id-"+a).each(function(){c.push(".thing.id-"+b(this).thing_id())});return b(c.join(", "))};b.fn.things=function(){return this.find(b.map(arguments,function(a){return".thing.id-"+a}).join(", "))};b.listing=function(a){a=a||"";if(a.slice(0,1)=="#"||a.slice(0,1)==".")a=a.slice(1,a.length);var c=a;a.slice(0,9)!="siteTable"?c="siteTable"+(a?"_"+a:""):a=a.slice(10,a.length);var d=b("#"+c).filter(":first");d.length==0&&(d=b.things(a).find(".child").append(document.createElement("div")).children(":last").addClass("sitetable").attr("id",
c));return d};var l=function(){};b.fn.set_thing_init=function(a){l=a;b(this).find(".thing:not(.stub)").each(function(){a(this)})};b.fn.new_thing_child=function(a,c){var d=this.thing_id(),e=c?b.listing(d):this.thing().find(".child:first");return(typeof a=="string"?e.prepend(a).children(":first"):a.hide().prependTo(e).show().find('input[name="parent"]').val(d).end()).randomize_ids()};b.fn.randomize_ids=function(){var a=(Math.random()+"").split(".")[1];b(this).find("*[id]").each(function(){b(this).attr("id",
b(this).attr("id")+a)}).end().find("label").each(function(){b(this).attr("for",b(this).attr("for")+a)});return b(this)};b.fn.replace_things=function(a,c,d,e){var g=b(".midcol:visible:first").css("width");b(".rank:visible:first").css("width");var h=this;return b.map(a,function(a){var i=a.data,a=b(h).things(i.id);e&&(a=a.filter(".stub"));if(a.length==0){var f=b.things(i.parent);f.length&&(a=b("<div></div>"),f.find(".child:first").append(a))}a.after(b.unsafe(i.content));i=a.next();b.defined(g)&&i.find(".midcol").css("width",
g).end().find(".rank").css("width",g);c&&(i.show().children(".midcol, .entry").hide().end().children(".child:first").html(a.children(".child:first").remove().html()).end(),d&&(a.hide(),i.children(".midcol, .entry").show()),i.find(".rank:first").html(a.find(".rank:first").html()));d?(a.hide(),c?i.children(".midcol, .entry").show():i.show()):i.hide();a.remove();l(i);return i})};b.insert_things=function(a,c){return b.map(a,function(a){var a=a.data,e=b(".midcol:visible:first").css("width"),g=b(".rank:visible:first").css("width"),
h=b.listing(a.parent),h=c?h.append(b.unsafe(a.content)).children(".thing:last"):h.prepend(b.unsafe(a.content)).children(".thing:first");h.find(".midcol").css("width",e);h.find(".rank").css("width",g);l(h.hide().show());return h})};b.fn.delete_table_row=function(a){var c=this.parents("tr:first").get(0),d=this.parents("table").get(0);c?b(c).fadeOut(function(){d.deleteRow(c.rowIndex);a&&a()}):a&&a()};b.fn.insert_table_rows=function(a,c){var d=this.is("table")?this.filter("table"):this.parents("table:first");
b.map(d.get(),function(e){b.map(a,function(a){var d=c;d<0&&(d=Math.max(e.rows.length+d+1,0));var d=Math.min(d,e.rows.length),f=e.insertRow(d);b(f).hide().attr("id",a.id).addClass(a.css_class);b.map(a.cells,function(a){b(f.insertCell(f.cells.length)).html(b.unsafe(a))});b(f).fadeIn()})});return this};b.set_tracker=function(a,c,d){reddit.trackers[a]={show:c,click:d};b.things(a).filter(":visible").show()};b.fn.captcha=function(a){var b=this.find(".capimage");a&&b.attr("src","http://"+reddit.ajax_domain+
"/captcha/"+a+".png").parents("form").find('input[name="iden"]').val(a);return b};b.fn.insertAtCursor=function(a){return b(this).filter("textarea").each(function(){var c=b(this).get(0),d=c.scrollTop;if(document.selection)c.focus(),document.selection.createRange().text=a;else if(c.selectionStart){var e=c.selectionStart;c.value=c.value.substring(0,c.selectionStart)+a+c.value.substring(c.selectionEnd,c.value.length);e+=a.length;c.setSelectionRange(e,e)}else c.value+=a;if(c.scrollHeight)c.scrollTop=d;
b(this).focus()}).end()};b.fn.select_line=function(a){return b(this).filter("textarea").each(function(){var c="\n",d=1,e=0;b.browser.msie&&(c="\r",d=0,e=1);for(var c=b(this).val().split(c),g=0;g<a-1;g++)e+=c[g].length+d;g=e;a<=c.length&&(g+=c[a-1].length+d);b(this).focus();this.createTextRange?(d=this.createTextRange(),d.move("character",e),e=this.createTextRange(),e.move("character",g),d.setEndPoint("StartToEnd",e),d.select()):this.selectionStart&&this.setSelectionRange(e,g);if(this.scrollHeight)this.scrollTop=
(a-2)*(this.scrollHeight/c.length)})};b.apply_stylesheet=function(a){var c=b("head").children("link[title], style[title]").filter(":first").attr("title")||"preferred stylesheet";if(document.styleSheets[0].cssText)for(var d=document.styleSheets,e=0;e<d.length;e++){if(d[e].title==c){d[e].cssText=a;break}}else b("head").children('*[title="'+c+'"]').remove(),b("head").append("<style type='text/css' media='screen' title='"+c+"'>"+a+"</style>")};b.rehighlight_new_comments=function(){checked=b(".comment-visits-box input:checked");
checked.length>0&&highlight_new_comments(checked[0].value)};var f;b.default_cookie_domain=function(a){b.defined(a)&&(f=a);return f};var j="_";b.cookie_name_prefix=function(a){b.defined(a)&&(j=a+"_");return j};b.cookie_test=function(){var a=(Math.random()+"").split(".")[1];b.cookie_write({name:"test",data:a});if(b.cookie_read("test").data==a)return b.cookie_erase("test"),!0};b.cookie_erase=function(a){a.data="";a.expires=-1;b.cookie_write(a)};b.cookie_write=function(a){if(a.name){var c=b.with_default(a.data,
""),c=typeof c=="string"?c:b.toJSON(c),c=j+a.name+"="+escape(c);if(b.defined(a.expires)){var d=a.expires;if(typeof d=="number"){var e=new Date;e.setTime(e.getTime()+d*864E5);d=e}b.defined(d.toGMTString)&&(d=d.toGMTString());c+="; expires="+d}d=b.with_default(a.domain,f);b.defined(d)&&(c+="; domain="+d);c+="; path="+b.with_default(a.path,"/");document.cookie=c}};b.cookie_read=function(a,c){for(var d=(c||j)+a+"=",e=document.cookie.split(";"),g="",h=e.length-1;h>=0;h--){for(var f=e[h];f.charAt(0)==" ";)f=
f.substring(1,f.length);if(f.indexOf(d)==0){g=unescape(f.substring(d.length,f.length));try{g=b.secureEvalJSON(g)}catch(i){}break}}return{name:a,data:g}}})(jQuery);
$(function(){function b(a){if(a.substring(0,1)!="#")return"#"+a;return a}function n(){l==1?($(".arrow.up").addClass("upmod").removeClass("up"),$(".arrow.downmod").removeClass("downmod").addClass("down"),$(".entry").removeClass("dislikes").addClass("likes")):l==-1?($(".arrow.upmod").removeClass("upmod").addClass("up"),$(".arrow.down").addClass("downmod").removeClass("down"),$(".entry").addClass("dislikes").removeClass("likes")):($(".arrow.upmod").removeClass("upmod").addClass("up"),$(".arrow.downmod").removeClass("downmod").addClass("down"),
$(".entry").removeClass("dislikes").removeClass("likes"))}function m(a,b,c){var d="http:///www.reddit.com";b&&(d+="/r/"+b);d+="/submit?url="+encodeURIComponent(a);c&&(d+="&title="+encodeURIComponent(c));return d}reddit.external_frame=!0;var l=null;$(".arrow.up").click(function(){l=$(this).hasClass("up")?1:0;n()});$(".arrow.down").click(function(){l=$(this).hasClass("down")?-1:0;n()});var f=document.location.search;f&&f.substring(0,1)=="?"&&(f=f.slice(1,f.length));var j={};$.map(f.split("&"),function(a){a=
$.map(a.split("="),function(a){return $.websafe(decodeURIComponent(a))});j[a[0]]=a[1]});$("a").attr("href",m(j.url,j.sr,j.title));j.bgcolor&&$("body").css("background-color",b(j.bgcolor));j.bordercolor&&$(".blog").css("border-color",b(j.bordercolor));var a=j.newwindow?"_blank":"_top";$("a").attr("target",a);var f=$("body").width(),c=$("body").height();$(".button").width(f?f+"px":"100%");$(".button").height(c?c+"px":"100%");var d=function(){var b=m(j.url,j.sr,j.title);$(".score:visible").fadeOut(function(){$(".score").html('<a class="submit" target="'+
a+'" href="'+b+'">submit</a>');$(this).fadeIn().css("display","")});$(".bling a, a.bling").attr("href",b);$(".arrow").each(function(){$(this).get(0).onclick=function(){a=="_blank"?window.open(b,a):window.parent.location=b}})},f={type:"GET",url:null,data:{},success:function(a){try{var b=a.data.modhash;if(b)reddit.logged=!0,reddit.modhash=b;var c=a.data.children[0].data,a=function(a){return $(".score:visible").fadeOut(function(){a();$(this).fadeIn().css("display","")})};$(".thing").addClass("id-"+c.name);
$(".bling a, a.bling").attr("href","http://www.reddit.com"+c.permalink);c.likes?(real_state=1,a(function(){$(".score.likes").html(point_label(c.score));$(".score.unvoted").html(point_label(c.score-1));$(".score.dislikes").html(point_label(c.score-2))})):c.likes==!1?(real_state=-1,a(function(){$(".score.likes").html(point_label(c.score+2));$(".score.unvoted").html(point_label(c.score+1));$(".score.dislikes").html(point_label(c.score))})):(real_state=0,a(function(){$(".score.likes").html(point_label(c.score+
1));$(".score.unvoted").html(point_label(c.score));$(".score.dislikes").html(point_label(c.score-1))}));$(".arrow").unbind("click").click(function(){$(this).vote("",set_score,!0)});reddit.logged&&l!=real_state&&(l!=null?$.request("vote",{id:c.name,dir:l}):l=real_state);n();finalize_thing(c)}catch(f){d()}},error:d},a="/button_info.json";j.sr&&(a="/r/"+j.sr+a);$.cookie_read("session","reddit_").data?(f.url=a,f.dataType="json"):(f.url="http://buttons.reddit.com"+a,f.dataType=f.jsonp="jsonp",f.jsonpCallback=
"buttonInfoCb",f.cache=!0);if($.defined(j.url))f.data.url=j.url;if($.defined(j.id))f.data.id=j.id;$.ajax(f)});function point_label(b){return b}function set_score(){}function finalize_thing(){};
