jQuery.cookie=function(b,l,f){if(arguments.length>1&&String(l)!=="[object Object]"){f=jQuery.extend({},f);if(l===null||l===void 0)f.expires=-1;if(typeof f.expires==="number"){var k=f.expires,c=f.expires=new Date;c.setDate(c.getDate()+k)}l=String(l);return document.cookie=[encodeURIComponent(b),"=",f.raw?l:encodeURIComponent(l),f.expires?"; expires="+f.expires.toUTCString():"",f.path?"; path="+f.path:"",f.domain?"; domain="+f.domain:"",f.secure?"; secure":""].join("")}f=l||{};c=f.raw?function(b){return b}:
decodeURIComponent;return(k=RegExp("(?:^|; )"+encodeURIComponent(b)+"=([^;]*)").exec(document.cookie))?c(k[1]):null};
(function(b){function l(){return function(a){if(a.jquery){var d={};d[0]=jQuery;b.map(a.jquery,function(a){var h=a[0],g=a[1],j=a[2],a=a[3];if(typeof a=="string")a=b.unsafe(a);else for(var m=0;a.length&&m<a.length;m++)a[m]=b.unsafe(a[m]);j=="call"?d[g]=d[h].apply(d[h]._obj,a):j=="attr"?(d[g]=d[h][a],d[g]?d[g]._obj=d[h]:b.debug("unrecognized")):j=="refresh"?b.refresh():b.debug("unrecognized")})}}}b.log=function(a){window.console?window.console.debug?window.console.debug(a):window.console.log&&window.console.log(a):
alert(a)};b.debug=function(a){if(b.with_default(reddit.debug,!1))return b.log(a)};b.fn.debug=function(){b.debug(b(this));return b(this)};b.redirect=function(a){window.location=a};b.fn.redirect=function(a){b(this).filter("form").find(".status").show().html("redirecting...");if(b(this).attr("target")=="_top"){for(var d=window;d!=d.parent;)d=d.parent;d.location=a}else b.redirect(a);return b(this)};b.refresh=function(){window.location.reload(!0)};b.defined=function(a){return typeof a!="undefined"};b.with_default=
function(a,d){return b.defined(a)?a:d};b.websafe=function(a){typeof a=="string"&&(a=a.replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/>/g,"&gt;").replace(/</g,"&lt;"));return a||""};b.unsafe=function(a){typeof a=="string"&&(a=a.replace(/&quot;/g,'"').replace(/&gt;/g,">").replace(/&lt;/g,"<").replace(/&amp;/g,"&"));return a||""};b.uniq=function(a,b){for(var e=[],h={},g=b?b:a.length,j=0;j<a.length&&e.length<g;j++)h[a[j]]||(h[a[j]]=!0,e.push(a[j]));return e};(function(a,d){b.fn.show=function(d,
h){b(this).trigger("onshow");return a.call(this,d,h)};b.fn.hide=function(a,h){b(this).trigger("onhide");return d.call(this,a,h)}})(b.fn.show,b.fn.hide);var f={};b.request=function(a,d,e,h,g,j,m){var n=a,c=e;if(!(rate_limit(a)||window!=window.top&&!reddit.cnameframe&&!reddit.external_frame)){if(!(c=!b.with_default(h,!1)))c=f[n]?!1:f[n]=!0;h=c;d=b.with_default(d,{});e=b.with_default(e,l(n));g=b.with_default(g,"json");typeof e!="function"&&(e=l(n));c=function(a){delete f[n];return e(a)};errorhandler_in=
b.with_default(m,function(){});m=function(a){delete f[n];return errorhandler_in(a)};j=b.with_default(j,!1);if(reddit.post_site)d.r=reddit.post_site;if(reddit.cnameframe)d.cnameframe=1;if(reddit.logged)d.uh=reddit.modhash;d.renderstyle=reddit.renderstyle;h&&b.ajax({type:j?"GET":"POST",url:"/api/"+a,data:d,success:c,error:m,dataType:g})}};rate_limit=function(){var a={vote:333,comment:5E3,ignore:0,ban:0,unban:0,assignad:0},d={},e=b.defined,h=b.with_default,g=Date;return function(b){var m=new g,c=d[b],
f=h(a[b],333);d[b]=m;return e(c)&&m-c<f}}();b.fn.vote=function(a,d,e,h){if(reddit.logged&&b(this).hasClass("arrow")){var g=b(this).hasClass("up")?1:b(this).hasClass("down")?-1:0,j=b(this).all_things_by_id(),m=j.children().not(".child").find(".arrow"),c=g==1?"up":"upmod";m.filter("."+c).removeClass(c).addClass(g==1?"upmod":"up");c=g==-1?"down":"downmod";m.filter("."+c).removeClass(c).addClass(g==-1?"downmod":"down");reddit.logged&&(j.each(function(){var a=b(this).find(".entry:first, .midcol:first");
g>0?a.addClass("likes").removeClass("dislikes unvoted"):g<0?a.addClass("dislikes").removeClass("likes unvoted"):a.addClass("unvoted").removeClass("likes dislikes")}),b.defined(h)||(h=j.filter(":first").thing_id(),a+=e?"":"-"+h,b.request("vote",{id:h,dir:g,vh:a})));d&&d(j,g)}};b.fn.show_unvotable_message=function(){b(this).thing().find(".entry:first .unvotable-message").css("display","inline-block")};b.fn.thing=function(){return this.parents(".thing:first")};b.fn.all_things_by_id=function(){return this.thing().add(b.things(this.thing_id()))};
b.fn.thing_id=function(a){var a=b.with_default(a,"thing"),d=this.hasClass("thing")?this:this.thing();a!="thing"&&(d=d.find("."+a+":first"));if(d.length)return a=b.grep(d.get(0).className.match(/\S+/g),function(a){return a.match(/^id-/)}),a.length?a[0].slice(3,a[0].length):"";return""};b.things=function(){var a=b.map(arguments,function(a){return".thing.id-"+a}).join(", ");return b(a)};b.fn.same_author=function(){var a=b(this).thing_id("author"),d=[];b(".author.id-"+a).each(function(){d.push(".thing.id-"+
b(this).thing_id())});return b(d.join(", "))};b.fn.things=function(){return this.find(b.map(arguments,function(a){return".thing.id-"+a}).join(", "))};b.listing=function(a){a=a||"";if(a.slice(0,1)=="#"||a.slice(0,1)==".")a=a.slice(1,a.length);var d=a;a.slice(0,9)!="siteTable"?d="siteTable"+(a?"_"+a:""):a=a.slice(10,a.length);var e=b("#"+d).filter(":first");e.length==0&&(e=b.things(a).find(".child").append(document.createElement("div")).children(":last").addClass("sitetable").attr("id",d));return e};
var k=function(){};b.fn.set_thing_init=function(a){k=a;b(this).find(".thing:not(.stub)").each(function(){a(this)})};b.fn.new_thing_child=function(a,d){var e=this.thing_id(),h=d?b.listing(e):this.thing().find(".child:first");return(typeof a=="string"?h.prepend(a).children(":first"):a.hide().prependTo(h).show().find('input[name="parent"]').val(e).end()).randomize_ids()};b.fn.randomize_ids=function(){var a=(Math.random()+"").split(".")[1];b(this).find("*[id]").each(function(){b(this).attr("id",b(this).attr("id")+
a)}).end().find("label").each(function(){b(this).attr("for",b(this).attr("for")+a)});return b(this)};b.fn.replace_things=function(a,d,e,h){var g=b(".midcol:visible:first").css("width");b(".rank:visible:first").css("width");var c=this;return b.map(a,function(a){var f=a.data,a=b(c).things(f.id);h&&(a=a.filter(".stub"));if(a.length==0){var i=b.things(f.parent);i.length&&(a=b("<div></div>"),i.find(".child:first").append(a))}a.after(b.unsafe(f.content));f=a.next();b.defined(g)&&f.find(".midcol").css("width",
g).end().find(".rank").css("width",g);d&&(f.show().children(".midcol, .entry").hide().end().children(".child:first").html(a.children(".child:first").remove().html()).end(),e&&(a.hide(),f.children(".midcol, .entry").show()),f.find(".rank:first").html(a.find(".rank:first").html()));e?(a.hide(),d?f.children(".midcol, .entry").show():f.show()):f.hide();a.remove();k(f);return f})};b.insert_things=function(a,d){return b.map(a,function(a){var a=a.data,h=b(".midcol:visible:first").css("width"),g=b(".rank:visible:first").css("width"),
c=b.listing(a.parent),c=d?c.append(b.unsafe(a.content)).children(".thing:last"):c.prepend(b.unsafe(a.content)).children(".thing:first");c.find(".midcol").css("width",h);c.find(".rank").css("width",g);k(c.hide().show());return c})};b.fn.delete_table_row=function(a){var d=this.parents("tr:first").get(0),e=this.parents("table").get(0);d?b(d).fadeOut(function(){e.deleteRow(d.rowIndex);a&&a()}):a&&a()};b.fn.insert_table_rows=function(a,d){var e=this.is("table")?this.filter("table"):this.parents("table:first");
b.map(e.get(),function(e){b.map(a,function(a){var c=d;c<0&&(c=Math.max(e.rows.length+c+1,0));var c=Math.min(c,e.rows.length),f=e.insertRow(c);b(f).hide().attr("id",a.id).addClass(a.css_class);b.map(a.cells,function(a){b(f.insertCell(f.cells.length)).html(b.unsafe(a))});b(f).fadeIn()})});return this};b.fn.captcha=function(a){var b=this.find(".capimage");a&&b.attr("src","/captcha/"+a+".png").parents("form").find('input[name="iden"]').val(a);return b};b.fn.insertAtCursor=function(a){return b(this).filter("textarea").each(function(){var d=
b(this).get(0),e=d.scrollTop;if(document.selection)d.focus(),document.selection.createRange().text=a;else if(d.selectionStart){var c=d.selectionStart;d.value=d.value.substring(0,d.selectionStart)+a+d.value.substring(d.selectionEnd,d.value.length);c+=a.length;d.setSelectionRange(c,c)}else d.value+=a;if(d.scrollHeight)d.scrollTop=e;b(this).focus()}).end()};b.fn.select_line=function(a){return b(this).filter("textarea").each(function(){var d="\n",e=1,c=0;b.browser.msie&&(d="\r",e=0,c=1);for(var d=b(this).val().split(d),
g=0;g<a-1;g++)c+=d[g].length+e;g=c;a<=d.length&&(g+=d[a-1].length+e);b(this).focus();this.createTextRange?(e=this.createTextRange(),e.move("character",c),c=this.createTextRange(),c.move("character",g),e.setEndPoint("StartToEnd",c),e.select()):this.selectionStart&&this.setSelectionRange(c,g);if(this.scrollHeight)this.scrollTop=(a-2)*(this.scrollHeight/d.length)})};b.apply_stylesheet=function(a){var d=b("head").children("link[title], style[title]").filter(":first").attr("title")||"preferred stylesheet";
if(document.styleSheets[0].cssText)for(var e=document.styleSheets,c=0;c<e.length;c++){if(e[c].title==d){e[c].cssText=a;break}}else b("head").children('*[title="'+d+'"]').remove(),b("head").append("<style type='text/css' media='screen' title='"+d+"'>"+a+"</style>")};b.rehighlight_new_comments=function(){checked=b(".comment-visits-box input:checked");checked.length>0&&highlight_new_comments(checked[0].value)};var c;b.default_cookie_domain=function(a){a&&(c=a)};var i="_";b.cookie_name_prefix=function(a){a&&
(i=a+"_")};b.cookie_write=function(a){if(a.name){var d={};d.expires=a.expires;d.domain=a.domain||c;d.path=a.path||"/";var e=i+a.name,a=a.data;a===null||a==""?a=null:typeof a!="string"&&(a=JSON.stringify(a));b.cookie(e,a,d)}};b.cookie_read=function(a,d){var c=b.cookie((d||i)+a);try{c=JSON.parse(c)}catch(f){}return{name:a,data:c}}})(jQuery);
$(function(){function b(a){if(a.substring(0,1)!="#")return"#"+a;return a}function l(){k==1?($(".arrow.up").addClass("upmod").removeClass("up"),$(".arrow.downmod").removeClass("downmod").addClass("down"),$(".entry").removeClass("dislikes").addClass("likes")):k==-1?($(".arrow.upmod").removeClass("upmod").addClass("up"),$(".arrow.down").addClass("downmod").removeClass("down"),$(".entry").addClass("dislikes").removeClass("likes")):($(".arrow.upmod").removeClass("upmod").addClass("up"),$(".arrow.downmod").removeClass("downmod").addClass("down"),
$(".entry").removeClass("dislikes").removeClass("likes"))}function f(a,b,d){var c="http://www.reddit.com";b&&(c+="/r/"+b);c+="/submit?url="+encodeURIComponent(a);d&&(c+="&title="+encodeURIComponent(d));return c}reddit.external_frame=!0;var k=null;$(".arrow.up").click(function(){k=$(this).hasClass("up")?1:0;l()});$(".arrow.down").click(function(){k=$(this).hasClass("down")?-1:0;l()});var c=document.location.search;c&&c.substring(0,1)=="?"&&(c=c.slice(1,c.length));var i={};$.map(c.split("&"),function(a){a=
$.map(a.split("="),function(a){return $.websafe(decodeURIComponent(a))});i[a[0]]=a[1]});$("a").attr("href",f(i.url,i.sr,i.title));i.bgcolor&&$("body").css("background-color",b(i.bgcolor));i.bordercolor&&$(".blog").css("border-color",b(i.bordercolor));var a=i.newwindow?"_blank":"_top";$("a").attr("target",a);var d=function(){var b=f(i.url,i.sr,i.title);$(".score:visible").fadeOut(function(){$(".score").html('<a class="submit" target="'+a+'" href="'+b+'">submit</a>');$(this).fadeIn().css("display",
"")});$(".bling a, a.bling").attr("href",b);$(".arrow").each(function(){$(this).get(0).onclick=function(){a=="_blank"?window.open(b,a):window.parent.location=b}})},c={type:"GET",url:null,data:{},success:function(a){try{var b=a.data.modhash;if(b)reddit.logged=!0,reddit.modhash=b;var c=a.data.children[0].data,a=function(a){return $(".score:visible").fadeOut(function(){a();$(this).fadeIn().css("display","")})};$(".thing").addClass("id-"+c.name);$(".bling a, a.bling").attr("href","http://www.reddit.com"+
c.permalink);c.likes?(real_state=1,a(function(){$(".score.likes").html(point_label(c.score));$(".score.unvoted").html(point_label(c.score-1));$(".score.dislikes").html(point_label(c.score-2))})):c.likes==!1?(real_state=-1,a(function(){$(".score.likes").html(point_label(c.score+2));$(".score.unvoted").html(point_label(c.score+1));$(".score.dislikes").html(point_label(c.score))})):(real_state=0,a(function(){$(".score.likes").html(point_label(c.score+1));$(".score.unvoted").html(point_label(c.score));
$(".score.dislikes").html(point_label(c.score-1))}));$(".arrow").unbind("click").click(function(){$(this).vote("",set_score,!0)});reddit.logged&&k!=real_state&&(k!=null?$.request("vote",{id:c.name,dir:k}):k=real_state);l();finalize_thing(c)}catch(f){d()}},error:d},a="/button_info.json";i.sr&&(a="/r/"+i.sr+a);$.cookie_read("session","reddit_").data?(c.url=a,c.dataType="json"):(c.url="http://buttons.reddit.com"+a,c.dataType=c.jsonp="jsonp",c.jsonpCallback="buttonInfoCb",c.cache=!0);if($.defined(i.url))c.data.url=
i.url;if($.defined(i.id))c.data.id=i.id;$.ajax(c)});function point_label(b){return b}function set_score(){}function finalize_thing(){};
